CREATE TABLE IF NOT EXISTS public.product_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id TEXT NOT NULL,
  product_id TEXT NOT NULL,
  product_name TEXT NOT NULL,
  customer_name TEXT NOT NULL,
  review_text TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT product_reviews_unique_reservation_product UNIQUE (reservation_id, product_id)
);

ALTER TABLE public.product_reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read product_reviews" ON public.product_reviews;
CREATE POLICY "Public read product_reviews"
  ON public.product_reviews
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Public insert product_reviews" ON public.product_reviews;
CREATE POLICY "Public insert product_reviews"
  ON public.product_reviews
  FOR INSERT
  WITH CHECK (true);