-- Migration: homepage videos for CollectionSection
-- Creates a table that stores the storage paths for homepage videos.
-- Upload the files first to bucket: portfolio-media/videos/
-- Expected files:
--   videos/lateral-izquierdo.mp4
--   videos/lateral-derecho.mp4
--   videos/macao-rancho.mp4

CREATE TABLE IF NOT EXISTS homepage_media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slot TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT,
  storage_path TEXT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT homepage_media_slot_check CHECK (
    slot IN ('macao-beach', 'horseback-riding', 'featured-large')
  )
);

CREATE OR REPLACE FUNCTION update_homepage_media_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_homepage_media_updated_at ON homepage_media;
CREATE TRIGGER trg_homepage_media_updated_at
  BEFORE UPDATE ON homepage_media
  FOR EACH ROW
  EXECUTE FUNCTION update_homepage_media_updated_at();

ALTER TABLE homepage_media ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read homepage_media" ON homepage_media;
CREATE POLICY "Public read homepage_media"
  ON homepage_media
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Authenticated write homepage_media" ON homepage_media;
CREATE POLICY "Authenticated write homepage_media"
  ON homepage_media
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

INSERT INTO homepage_media (slot, title, description, storage_path, sort_order, active)
VALUES
  (
    'macao-beach',
    'Macao Beach',
    'Vive la experiencia en los caminos de Macao',
    'videos/lateral-izquierdo.mp4',
    1,
    TRUE
  ),
  (
    'horseback-riding',
    'Horseback Riding',
    'Descubre los mejores paisajes en buggy',
    'videos/lateral-derecho.mp4',
    2,
    TRUE
  ),
  (
    'featured-large',
    'Adventure Experience',
    NULL,
    'videos/macao-rancho.mp4',
    3,
    TRUE
  )
ON CONFLICT (slot) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  storage_path = EXCLUDED.storage_path,
  sort_order = EXCLUDED.sort_order,
  active = EXCLUDED.active,
  updated_at = NOW();
